;Scintillation and Vantec Detectors
;Modified 03/07/2007 - Ping Yang - References: TH-Tube and TH-Detector
[COM1]
NAME=Computer
PORT=03f8
MODE=9600,N,8,1
HANDSHAKE=
CANCEL=24
COMMENT=rem
AUTO=n

[COM2]
NAME=Service
PORT=02f8
MODE=9600,N,8,1
HANDSHAKE=
CANCEL=24
COMMENT=rem
AUTO=n

; For SealedTube: Set "TUBEWIN=LowSpeedShutter" & "XRAYGEN=SealedTube"
; For RotatingAnode: Set TUBEWIN= & XRAYGEN= to blank string
; For RotaryShutter (SMART Shutter): Remove comment below
;[RS]
BASEADR=1C0
CFN=A0
CUR=2.00
DNLD=

; 3.04 Supports up to 4 different shutters ------------------------------------
; Safety Shutter is type 1
;[SHUTTER1]
NAME=RotatingAnodeShutter
TYPE=1
OPEN=DC1
STATUS=
OPENDELAY=0.050
CLOSEDELAY=0.030

; Experimental Shutter(s) is type 2
;[SHUTTER2]
NAME=RotaryShutter
TYPE=2
OPEN=SH1
STATUS=
OPENDELAY=0.014
CLOSEDELAY=0.007

;[SHUTTER2]
NAME=CustomShutter
TYPE=2
OPEN=OC256,1
STATUS=
OPENDELAY=0.020
CLOSEDELAY=0.010

;NAME=DivergenceSlit
;CONF_A=0238
;CONF_B=0000
;CONF_X=1001
;MTYPE=1
;BIASCUR=50
;BIASDELAY=250
;PHASECUR=0.3
;FSTEPS=200
;GEAR=200
;RESOL=0.2
;ECOUNTS=1
;SLOW=100
;FAST=200
;ATIME=1
;REF=185
;LOWER=-1
;UPPER=201
;POSERR=40
;MODULUS=0
;BACKLASH=0
;SLOWDOWN=0
;MOVELMT=10
;CCP=5
;CCI=0.02
;HOMEMARK=0
;KP=0
;KI=0
;KD=0,1
;KAFF=0
;KVFF=0
;KOUT=0
;ILMT=0
;SETTLEWND=0
;SETTLETIME=0
;RCURL=0
;RCURH=0
;OLCURL=0
;OLCURH=0
;NAME=AntiscatteringSlit
;CONF_A=0238
;CONF_B=0000
;CONF_X=1001
;MTYPE=1
;BIASCUR=50
;BIASDELAY=250
;PHASECUR=0.3
;FSTEPS=200
;GEAR=200
;RESOL=0.2
;ECOUNTS=1
;SLOW=100
;FAST=200
;ATIME=1
;REF=185
;LOWER=-1
;UPPER=201
;POSERR=40
;MODULUS=0
;BACKLASH=0
;SLOWDOWN=0
;MOVELMT=10
;CCP=5
;CCI=0.02
;HOMEMARK=0
;KP=0
;KI=0
;KD=0,1
;KAFF=0
;KVFF=0
;KOUT=0
;ILMT=0
;SETTLEWND=0
;SETTLETIME=0
;RCURL=0
;RCURH=0
;OLCURL=0
;OLCURH=0
[DEVICE]
NAME=D8
IRQ=5
SETUPTIME=1000

[WATER]
TYPE=4
CP=0.00
CI=0.00
CD=0.00
TEMP1=0.00
TEMP2=0.00
TEMP3=0.00
FLOW1=3.5
FLOW2=4
FLOW3=3.5
COND1=0.00
COND2=0.00
COND3=0.00
XFLOWSENSOR=640,0.0029
DTEMP=1.00

[DRIVE1]
NAME=TH-Tube
CONF_A=0030
CONF_B=ED00
CONF_X=5078
MTYPE=1
BIASCUR=50
BIASDELAY=250
PHASECUR=4
FSTEPS=200
GEAR=1
RESOL=0.0001
ECOUNTS=5000
SLOW=40
FAST=200
ATIME=2
REF=19.3148
LOWER=-10
UPPER=66
POSERR=0.01
MODULUS=0
BACKLASH=0
SLOWDOWN=0
MOVELMT=10
CCP=8
CCI=0.05
HOMEMARK=0
KP=0
KI=0
KD=0,1
KAFF=0
KVFF=0
KOUT=0
ILMT=0
SETTLEWND=0
SETTLETIME=0
RCURL=0
RCURH=0
OLCURL=0
OLCURH=0

[DRIVE2]
NAME=TH-Detector
CONF_A=0830
CONF_B=ED00
CONF_X=5078
MTYPE=1
BIASCUR=50
BIASDELAY=250
PHASECUR=4
FSTEPS=200
GEAR=1
RESOL=0.0001
ECOUNTS=5000
SLOW=40
FAST=400
ATIME=2
REF=22.9456
LOWER=-10
UPPER=120.1
POSERR=0.01
MODULUS=0
BACKLASH=0
SLOWDOWN=0
MOVELMT=10
CCP=8
CCI=0.05
HOMEMARK=0
KP=0
KI=0
KD=0,1
KAFF=0
KVFF=0
KOUT=0
ILMT=0
SETTLEWND=0
SETTLETIME=0
RCURL=0
RCURH=0
OLCURL=0
OLCURH=0

[DRIVE3]
NAME=Phi
CONF_A=0688
CONF_B=0000
CONF_X=5101
MTYPE=1
BIASCUR=50
BIASDELAY=250
PHASECUR=0.9
FSTEPS=200
GEAR=2
RESOL=0.0002
ECOUNTS=1
SLOW=200
FAST=1200
ATIME=0.2
REF=64.0935
LOWER=-360
UPPER=360
POSERR=0
MODULUS=0
BACKLASH=0
SLOWDOWN=0
MOVELMT=10
CCP=5
CCI=0.02
HOMEMARK=0
KP=0
KI=0
KD=0,1
KAFF=0
KVFF=0
KOUT=0
ILMT=0
SETTLEWND=0
SETTLETIME=0
RCURL=0
RCURH=0
OLCURL=0
OLCURH=0

[DRIVE4]
NAME=Psi
CONF_A=0A30
CONF_B=0000
CONF_X=4360
MTYPE=1
BIASCUR=50
BIASDELAY=250
PHASECUR=0.9
FSTEPS=200
GEAR=0.2
RESOL=0.0002
ECOUNTS=1
SLOW=60
FAST=180
ATIME=0.5
REF=-11.965
LOWER=-11
UPPER=90.1
POSERR=0
MODULUS=0
BACKLASH=0
SLOWDOWN=0
MOVELMT=10
CCP=20
CCI=0
HOMEMARK=0
KP=0
KI=0
KD=0,1
KAFF=0
KVFF=0
KOUT=0
ILMT=0
SETTLEWND=0
SETTLETIME=0
RCURL=0
RCURH=0
OLCURL=0
OLCURH=0

[DRIVE5]
NAME=X-Drive
CONF_A=08B8
CONF_B=0000
CONF_X=9560
MTYPE=1
BIASCUR=50
BIASDELAY=250
PHASECUR=0.9
FSTEPS=200
GEAR=1
RESOL=0.001
ECOUNTS=1
SLOW=2
FAST=10
ATIME=1
REF=41.049
LOWER=-40
UPPER=40
POSERR=0.2
MODULUS=0
BACKLASH=0
SLOWDOWN=0
MOVELMT=10
CCP=5
CCI=0.02
HOMEMARK=0
KP=0
KI=0
KD=0,1
KAFF=0
KVFF=0
KOUT=0
ILMT=0
SETTLEWND=0
SETTLETIME=0
RCURL=0
RCURH=0
OLCURL=0
OLCURH=0

[DRIVE6]
NAME=Y-Drive
CONF_A=08B8
CONF_B=0000
CONF_X=9560
MTYPE=1
BIASCUR=50
BIASDELAY=250
PHASECUR=0.9
FSTEPS=200
GEAR=1
RESOL=0.001
ECOUNTS=1
SLOW=2
FAST=10
ATIME=1
REF=41.023
LOWER=-40
UPPER=40
POSERR=0.2
MODULUS=0
BACKLASH=0
SLOWDOWN=0
MOVELMT=10
CCP=5
CCI=0.02
HOMEMARK=0
KP=0
KI=0
KD=0,1
KAFF=0
KVFF=0
KOUT=0
ILMT=0
SETTLEWND=0
SETTLETIME=0
RCURL=0
RCURH=0
OLCURL=0
OLCURH=0

[DRIVE7]
NAME=Z-Drive
CONF_A=0838
CONF_B=0000
CONF_X=9360
MTYPE=1
BIASCUR=50
BIASDELAY=250
PHASECUR=0.9
FSTEPS=200
GEAR=0.5
RESOL=0.0005
ECOUNTS=1
SLOW=0.1
FAST=0.2
ATIME=0.6
REF=-1.27
LOWER=-2
UPPER=3
POSERR=0
MODULUS=0
BACKLASH=0
SLOWDOWN=0
MOVELMT=5
CCP=5
CCI=0.02
HOMEMARK=0
KP=0
KI=0
KD=0,1
KAFF=0
KVFF=0
KOUT=0
ILMT=0
SETTLEWND=0
SETTLETIME=0
RCURL=0
RCURH=0
OLCURL=0
OLCURH=0

[DRIVE8]
NAME=Zoom
CONF_A=0A30
CONF_B=0000
CONF_X=9260
MTYPE=1
BIASCUR=50
BIASDELAY=500
PHASECUR=2
FSTEPS=200
GEAR=1.8
RESOL=0.0009
ECOUNTS=1
SLOW=0.2
FAST=1
ATIME=1
REF=0.85
LOWER=1
UPPER=7
POSERR=0
MODULUS=0
BACKLASH=0
SLOWDOWN=0
MOVELMT=10
CCP=5
CCI=0.02
HOMEMARK=0
KP=0
KI=0
KD=0,1
KAFF=0
KVFF=0
KOUT=0
ILMT=0
SETTLEWND=0
SETTLETIME=0
RCURL=0
RCURH=0
OLCURL=0
OLCURH=0

[UIOB1]
BASEADR=100
SLIT=
TUBEWIN=LowSpeedShutter
XRAYGEN=K780
TERMINAL=QTERMII
DAC1=0

[AIB1]
BASEADR=560
DRIVER1=TH-Tube
DRIVER2=TH-Detector
POWER=24

[AIB2]
BASEADR=960
DRIVER1=X-Drive
DRIVER2=Y-Drive
DRIVER3=Z-Drive
DRIVER4=Zoom
POWER=24

[AIB3]
BASEADR=980
DRIVER1=Phi
DRIVER2=Psi
DRIVER3=
DRIVER4=
POWER=24

